/**
 * Font Awesome Plugin for Nuxt 3
 * Official Font Awesome integration using @fortawesome/vue-fontawesome
 */
import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Prevent Font Awesome from adding its CSS (we'll import it manually)
config.autoAddCss = false

// Import Solid icons
import {
    faHome,
    faGaugeHigh,
    faChartBar,
    faChartPie,
    faChartLine,
    faTicket,
    faClipboard,
    faClipboardCheck,
    faClipboardList,
    faCircleCheck,
    faCircleXmark,
    faCircleExclamation,
    faTriangleExclamation,
    faCircleInfo,
    faClock,
    faCalendar,
    faCalendarDays,
    faUser,
    faUsers,
    faUserGroup,
    faUserDoctor,
    faUserNurse,
    faUserGear,
    faBuilding,
    faBuildingColumns,
    faHospital,
    faPlus,
    faPlusCircle,
    faMinus,
    faRotate,
    faArrowsRotate,
    faMagnifyingGlass,
    faFilter,
    faPen,
    faPenToSquare,
    faTrash,
    faTrashCan,
    faBars,
    faChevronLeft,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faArrowLeft,
    faArrowRight,
    faArrowUpRightFromSquare,
    faGear,
    faGears,
    faShieldHalved,
    faServer,
    faDatabase,
    faCloud,
    faHardDrive,
    faComment,
    faComments,
    faMessage,
    faBell,
    faEnvelope,
    faEye,
    faEyeSlash,
    faDownload,
    faUpload,
    faRightFromBracket,
    faRightToBracket,
    faBolt,
    faStar,
    faFile,
    faFileLines,
    faFolder,
    faFolderOpen,
    faSpinner,
    faCircleNotch,
    faCheck,
    faXmark,
    faInfo,
    faQuestion,
    faExclamation,
    faCog,
    faCogs,
    faWrench,
    faScrewdriverWrench,
    faStethoscope,
    faPills,
    faSyringe,
    faHeartPulse,
    faAmbulance,
    faBed,
    faUserInjured,
    faClockRotateLeft,
    faListCheck,
    faTableColumns,
    faCircle,
    faSquare,
    faPlay,
    faPause,
    faStop,
    faForward,
    faBackward,
    faExpand,
    faCompress,
    faMaximize,
    faMinimize,
    faAngleLeft,
    faAngleRight,
    faAngleDown,
    faAngleUp,
    faAnglesLeft,
    faAnglesRight,
    faEllipsis,
    faEllipsisVertical,
    faGripVertical,
    faLayerGroup,
    faTag,
    faTags,
    faBookmark,
    faFlag,
    faLocationDot,
    faPhone,
    faPhoneVolume,
    faGlobe,
    faLanguage,
    faSun,
    faMoon,
    faPalette,
    faRobot,
    faHandshake,
    faReceipt,
    faCreditCard,
    faMoneyBill,
    faDollarSign,
    faPercent,
    faHashtag,
    faAt,
    faLink,
    faUnlink,
    faPaperclip,
    faImage,
    faImages,
    faCamera,
    faVideo,
    faMicrophone,
    faVolumeHigh,
    faVolumeLow,
    faVolumeXmark,
    faPrint,
    faShareNodes,
    faCopy,
    faScissors,
    faClone,
    faLock,
    faLockOpen,
    faKey,
    faFingerprint,
    faUserShield,
    faShield,
    faBan,
    faSlash,
    faCircleHalfStroke,
    faToggleOn,
    faToggleOff,
    faSort,
    faSortUp,
    faSortDown,
    faArrowUp,
    faArrowDown,
    faArrowUpWideShort,
    faArrowDownWideShort,
    faTableList,
    faTable,
    faGrip,
    faList,
    faListUl,
    faListOl,
    faIndent,
    faOutdent,
    faAlignLeft,
    faAlignCenter,
    faAlignRight,
    faAlignJustify,
    faBold,
    faItalic,
    faUnderline,
    faStrikethrough,
    faCode,
    faTerminal,
    faBug,
    faVial,
    faFlask,
    faMicroscope,
    faXRay,
    faLungs,
    faBrain,
    faHeart,
    faTooth,
    faBone,
    faEarListen,
    faHandHoldingMedical,
    faBriefcaseMedical,
    faKitMedical,
    faNotesMedical,
    faFileMedical,
    faFilePrescription,
    faFileWaveform,
    faHouseMedical,
    faSquareH,
    faHouseMedicalFlag,
    faPersonDotsFromLine,
    faWheelchair,
    faCrutch,
    faHourglassHalf,
    faHourglassStart,
    faHourglassEnd,
    faStopwatch,
} from '@fortawesome/free-solid-svg-icons'

// Import Regular icons (outline style)
import {
    faCircle as farCircle,
    faSquare as farSquare,
    faClock as farClock,
    faCalendar as farCalendar,
    faUser as farUser,
    faComment as farComment,
    faComments as farComments,
    faMessage as farMessage,
    faBell as farBell,
    faEnvelope as farEnvelope,
    faEye as farEye,
    faEyeSlash as farEyeSlash,
    faFile as farFile,
    faFileLines as farFileLines,
    faFolder as farFolder,
    faFolderOpen as farFolderOpen,
    faBookmark as farBookmark,
    faFlag as farFlag,
    faImage as farImage,
    faImages as farImages,
    faCopy as farCopy,
    faClone as farClone,
    faCircleCheck as farCircleCheck,
    faCircleXmark as farCircleXmark,
    faTrashCan as farTrashCan,
    faPenToSquare as farPenToSquare,
    faClipboard as farClipboard,
    faHeart as farHeart,
    faStar as farStar,
    faFaceSmile as farFaceSmile,
    faFaceFrown as farFaceFrown,
    faFaceMeh as farFaceMeh,
    faHourglass as farHourglass,
} from '@fortawesome/free-regular-svg-icons'

// Add all icons to the library
library.add(
    // Solid icons
    faHome, faGaugeHigh, faChartBar, faChartPie, faChartLine,
    faTicket, faClipboard, faClipboardCheck, faClipboardList,
    faCircleCheck, faCircleXmark, faCircleExclamation, faTriangleExclamation, faCircleInfo,
    faClock, faCalendar, faCalendarDays,
    faUser, faUsers, faUserGroup, faUserDoctor, faUserNurse, faUserGear,
    faBuilding, faBuildingColumns, faHospital,
    faPlus, faPlusCircle, faMinus, faRotate, faArrowsRotate,
    faMagnifyingGlass, faFilter, faPen, faPenToSquare, faTrash, faTrashCan,
    faBars, faChevronLeft, faChevronRight, faChevronDown, faChevronUp,
    faArrowLeft, faArrowRight, faArrowUpRightFromSquare,
    faGear, faGears, faShieldHalved, faServer, faDatabase, faCloud, faHardDrive,
    faComment, faComments, faMessage, faBell, faEnvelope,
    faEye, faEyeSlash, faDownload, faUpload, faRightFromBracket, faRightToBracket,
    faBolt, faStar, faFile, faFileLines, faFolder, faFolderOpen,
    faSpinner, faCircleNotch, faCheck, faXmark, faInfo, faQuestion, faExclamation,
    faCog, faCogs, faWrench, faScrewdriverWrench,
    faStethoscope, faPills, faSyringe, faHeartPulse, faAmbulance, faBed, faUserInjured,
    faClockRotateLeft, faListCheck, faTableColumns,
    faCircle, faSquare, faPlay, faPause, faStop, faForward, faBackward,
    faExpand, faCompress, faMaximize, faMinimize,
    faAngleLeft, faAngleRight, faAngleDown, faAngleUp, faAnglesLeft, faAnglesRight,
    faEllipsis, faEllipsisVertical, faGripVertical, faLayerGroup,
    faTag, faTags, faBookmark, faFlag, faLocationDot, faPhone, faPhoneVolume,
    faGlobe, faLanguage, faSun, faMoon, faPalette,
    faRobot, faHandshake, faReceipt, faCreditCard, faMoneyBill, faDollarSign, faPercent,
    faHashtag, faAt, faLink, faUnlink, faPaperclip,
    faImage, faImages, faCamera, faVideo, faMicrophone, faVolumeHigh, faVolumeLow, faVolumeXmark,
    faPrint, faShareNodes, faCopy, faScissors, faClone,
    faLock, faLockOpen, faKey, faFingerprint, faUserShield, faShield, faBan, faSlash,
    faCircleHalfStroke, faToggleOn, faToggleOff,
    faSort, faSortUp, faSortDown, faArrowUp, faArrowDown, faArrowUpWideShort, faArrowDownWideShort,
    faTableList, faTable, faGrip, faList, faListUl, faListOl, faIndent, faOutdent,
    faAlignLeft, faAlignCenter, faAlignRight, faAlignJustify,
    faBold, faItalic, faUnderline, faStrikethrough,
    faCode, faTerminal, faBug, faVial, faFlask, faMicroscope, faXRay,
    faLungs, faBrain, faHeart, faTooth, faBone, faEarListen,
    faHandHoldingMedical, faBriefcaseMedical, faKitMedical, faNotesMedical,
    faFileMedical, faFilePrescription, faFileWaveform,
    faHouseMedical, faSquareH, faHouseMedicalFlag, faPersonDotsFromLine,
    faWheelchair, faCrutch,
    faHourglassHalf, faHourglassStart, faHourglassEnd, faStopwatch,

    // Regular icons (prefix with 'far')
    farCircle, farSquare, farClock, farCalendar, farUser,
    farComment, farComments, farMessage, farBell, farEnvelope,
    farEye, farEyeSlash, farFile, farFileLines, farFolder, farFolderOpen,
    farBookmark, farFlag, farImage, farImages, farCopy, farClone,
    farCircleCheck, farCircleXmark, farTrashCan, farPenToSquare, farClipboard,
    farHeart, farStar, farFaceSmile, farFaceFrown, farFaceMeh, farHourglass
)

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
    nuxtApp.vueApp.component('FaIcon', FontAwesomeIcon)
})
